spring:
  data:
    mongodb:
      port: 8099
      database: hw_db
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: liquibase/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
mongock:
  runner-type: InitializingBean
  change-logs-scan-package: ru.otus.hw.mongo.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local