server:
  port: 8189
  servlet:
    context-path: /library
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mainDb
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: liquibase/changelog.xml