spring:
  data:
    mongodb:
      port: 8099
      database: hw_db
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: InitializingBean
  change-logs-scan-package: ru.otus.hw.mongo.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local